### PR TITLE
Refinements to SyncKeyGen error and fault handling

### PR DESCRIPTION
**Pull request by c0gent**
* Add a new `AckMessageFault` type.
* Add new `sync_key_gen::Error` variants and remove `From` impl.

### CODE REVIEW

**Comment by c0gent** [comment]
If you like these changes you can approve and then click `Rebase and merge`. The commit will automatically be added to your branch/PR.

**Comment by DrPeterVanNostrand** [comment]
Ugg, idk why your tests are failing because of `mlock`. I'll look into it.

**Comment by c0gent** [comment]
Ok and I changed two of the `error!` logging macros back to `debug!` since the duplicate messages are normal.

**Comment by c0gent** [comment]
By the way, the tests pass for me. Because they fail on Travis it means tests are not correct and need to be fixed (in addition to whatever fixes you make to the `mlock` code). I'm sure you're probably already on top of it though :)

**Pull request closed without merging**
