### PR TITLE
Reorganize `dynamic_honey_badger` and `agreement` modules slightly.

### PR DESCRIPTION
**Pull request by c0gent**
* Move `CoinState` and `Agreement` definitions from `agreement/mod.rs`
  to `.../agreement.rs`.
* Move `DynamicHoneyBadger` definition from `dynamic_honey_badger/mod.rs`
  to `.../dynamic_honey_badger.rs`.

### CODE REVIEW

**Comment by c0gent** [comment]
Why did rustfmt change so many files?

**Comment by c0gent** [comment]
By the way I still hate rustfmt...

**Comment by afck** [comment]
Yes, you need to use the same rustfmt version as in the Travis config, sorry!

**Comment by c0gent** [comment]
Ah yeah, k

**Comment by c0gent** [comment]
Hmmm, I'm on `nightly-2018-07-13`:

```
active toolchain
----------------

nightly-2018-07-13-x86_64-unknown-linux-gnu (directory override for '/home/nick/src/hbbft')
```

It didn't change it back.

So I guess ummm... Just leave it?

**Comment by c0gent** [comment]
The newer style is a big improvement anyway (only 90397 more improvements to go before I'll like rustfmt).

**Comment by afck** [comment]
That's strange. Sure, if the CI passes, that's fine.
We should add a `rustfmt-toolchain` file that says `nightly-2018-07-13` (and probably make `.travis.yml` read from that file).
We could also upgrade to a later version soon

**Comment by c0gent** [comment]
Whoops, travis hadn't completed... I'll revert merge if there is a problem.

**Comment by c0gent** [comment]
Reverted in #185

**Pull request merged**
