### PR TITLE
added a Travis configuration file, fixed Clippy lints

### PR DESCRIPTION
**Pull request by afck**

### CODE REVIEW

**Comment by DrPeterVanNostrand** [comment]
If you can't apt-get the protoc binary, I have an open PR with protoc installation instructions that you can add to a shell script `./.travis/install_protoc.sh` and then add the following to the travis.yml:

```
before_install:
    ./.travis/install_protoc.sh
```

**Comment by vkomenda** [comment]
Hi @DrPeterVanNostrand! There is no .travis/ in https://github.com/poanetwork/hbbft/pull/9/
Please update your PR.

**Comment by DrPeterVanNostrand** [comment]
Hi @vkomenda ! I meant that when installing binaries with travis, generally you have to do some combination of curl/wget + chmod + mv + rm, it is common to put these instructions in a small shell script in the directory `.travis`.

So, if apt-get install didn't work, @afck could just copy the Debian `protoc` installation instructions in the README from [#9](https://github.com/poanetwork/hbbft/pull/9) into a shell script (for example `.travis/install_protoc.sh`, but the file could be located anywhere), and just call that script in `before_install` step.

**Comment by afck** [comment]
Thanks for the information! You're right, the version in Ubuntu seems to be too old (on my Debian stable here it worked just fine). I'll follow your instructions.

**Comment by afck** [comment]
That passed: https://travis-ci.com/poanetwork/hbbft/builds/72582202
(Not sure why GitHub isn't showing it.)

This would now also make Travis check Clippy and Rustfmt, but if you find them annoying, I'm happy with just the tests, too, of course.

**Pull request merged**
