### PR TITLE
Switch to 2018 edition idioms

### PR DESCRIPTION
**Pull request by DemiMarie**

### CODE REVIEW

**Comment by afck** [comment]
Yes, the version needs to be updated in `.travis.yml`.

**Comment by afck** [comment]
I made the rest of the required changes, removed most `extern crate`s and even made use of non-lexical lifetimes. :slightly_smiling_face:

**Comment by mbr** [comment]
The universe must hate me, releasing Rust 2018 while I'm in the midst of a huge refactoring (see #357). =/

**Comment by afck** [comment]
I actually think they might not even conflict that much, @mbr. This PR doesn't seem to touch many method signatures or calls related to the RNGs. :innocent:

**Pull request merged**
