### PR TITLE
Fix build if secure env vars are unavailable.

### LINKED ISSUE #202: CI fails on forks.
On forks of the repository, the secure environment variables are not available: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
Currently that makes CI fail: https://travis-ci.org/poanetwork/hbbft/builds/413664129
We should just skip this step on forks.

### PR DESCRIPTION
**Pull request by afck**
Closes #202

### CODE REVIEW

**Comment by c0gent** [comment]
Assuming this works, don't forget to select `Rebase and merge` :P

**Comment by c0gent** [comment]
Your syntax is incorrect.

**Comment by c0gent** [comment]
Sorry nevermind, you've fixed it.

**Comment by c0gent** [comment]
You have some extra semicolons in there though

**Comment by afck** [comment]
Which ones are extra? The one in the openssl line is the one I had to add because of Travis.
Seems to work on both PRs so far. Now I just have to remember to select "Rebase and merge"… :grin:

**Pull request merged**
