### PR TITLE
Added a NetworkInfo getter trait

### PR DESCRIPTION
**Pull request by vkomenda**
I added `HasNetworkInfo` to access the `netinfo` field of a `DistAlgorithm` if it has one. This can be used in the generic sender queue.

### CODE REVIEW

**Comment by c0gent** [comment]
You may want to consider renaming this trait as it goes against conventions (recently summed up nicely here: https://github.com/rust-lang-nursery/api-guidelines/issues/28#issuecomment-418509628).

The current name gives the impression that it's method returns a bool.

**Comment by c0gent** [comment]
Well the method is named `netinfo`...

**Comment by vkomenda** [comment]
Maybe just cloning the `Arc<NetworkInfo<N>>` into the sender queue is a better idea. There isn't anything that the queue has to access that is too large to be cloned, so I think I'll clone instead of adding the getter.

**Comment by vkomenda** [comment]
Closing this since the feature is not required.

**Pull request closed without merging**
